game:
  # ["Nim"|"Ledge"]: Game to play
  type: "Nim"
  # [1|2|3]: Starting player, 3 -> starting player randomly assigned.
  player_start_mode: 2

# Game specific parameters
  # Nim-specific parameters, only used when type: "Nim"
  stones: 100
  max_move: 80

  # Ledge-specific parameters, only used when type: "Ledge"
  length: 80
  copper_coins: 7

mcts:
  simulations: 300
  games: 100