game:
  # ["Nim"|"Ledge"]: Game to play
  type: "Ledge"
  # [1|2|3]: Starting player, 3 -> starting player randomly assigned.
  player_start_mode: 1

# Game specific parameters
  # Nim-specific parameters, only used when type: "Nim"
  stones: 15
  max_move: 3

  # Ledge-specific parameters, only used when type: "Ledge"
  length: 80
  copper_coins: 7

mcts:
  simulations: 420  # M
  games: 100        # G