game:
  # ["Nim"|"Ledge"]: Game to play
  type: "Ledge"
  # [1|2|3]: Starting player, 3 -> starting player randomly assigned.
  player_start_mode: 3 # P

# Game specific parameters
  # Nim-specific parameters, only used when type: "Nim"
  stones: 30     # N (MAX 255 because of state key conversion, may be upped by changing Nim.get_state())
  max_move: 7     # K

  # Ledge-specific parameters, only used when type: "Ledge"
  # [<list> | <length, copper_coins>] a specific initial board, or a randomly initialized one
  initial_board: # B_{init}
    - 0
    - 0
    - 1
    - 1
    - 0
    - 2
#    length: 10
#    copper_coins: 1

mcts:
  simulations: 300  # M
  games: 100        # G